### ISSUE TITLE
`get_family_name_txt_default_path` is missing

### ISSUE THREAD

**Issue by eggplants** [rskmoi/namedivider-python#21]
https://github.com/rskmoi/namedivider-python/blob/163509c191160104f6696d1901aff72b702ca8ff/examples/training/02_extract_feature.py#L8

Was `get_family_name_txt_default_path` replaced with something?

**Comment by rskmoi** [comment]
@eggplants 
Thank you for pointing this out. I have completed the fix. I had forgotten to update the source code during development.
